ifndef MK_CLEAN_MK
MK_CLEAN_MK=				TRUE

INCLUDER_MODULES_LIST=			config \
					applications \
					modules \
					tools \
					platform \
					doc

ifndef INCLUDER_PATH
$(error tool modbuild is not installed in your build system!)
else
include $(INCLUDER_PATH)
endif

CLEAN_PREFIX=				$(CONFIG_CLEAN_RULE)

CLEAN_APPLICATION_PREFIX=		$(CLEAN_PREFIX)_$(CONFIG_APPLICATION_PREFIX)
CLEAN_MODULE_PREFIX=			$(CLEAN_PREFIX)_$(CONFIG_MODULE_PREFIX)
CLEAN_TOOL_PREFIX=			$(CLEAN_PREFIX)_$(CONFIG_TOOL_PREFIX)

CLEAN_APPLICATIONS_PLATFORMS_STANDARD_LIST=	$(addprefix \
							$(CLEAN_PREFIX)_, \
							$(APPLICATIONS_PLATFORMS_STANDARD_LIST))

CLEAN_APPLICATIONS_PLATFORMS_NONSTANDARD_LIST=	$(addprefix \
							$(CLEAN_PREFIX)_, \
							$(APPLICATIONS_PLATFORMS_NONSTANDARD_LIST))

CLEAN_MODULES_PLATFORMS_STANDARD_LIST=		$(addprefix \
							$(CLEAN_PREFIX)_, \
							$(MODULES_PLATFORMS_STANDARD_LIST))

CLEAN_MODULES_PLATFORMS_NONSTANDARD_LIST=	$(addprefix \
							$(CLEAN_PREFIX)_, \
							$(MODULES_PLATFORMS_NONSTANDARD_LIST))

CLEAN_TOOLS_PLATFORMS_STANDARD_LIST=	$(addprefix \
						$(CLEAN_PREFIX)_, \
						$(TOOLS_PLATFORMS_STANDARD_LIST))

CLEAN_TOOLS_PLATFORMS_NONSTANDARD_LIST=	$(addprefix \
						$(CLEAN_PREFIX)_, \
						$(TOOLS_PLATFORMS_NONSTANDARD_LIST))

CLEAN_DOC_DEFAULT_HTML_LIST=		$(addprefix \
						$(CLEAN_PREFIX)_, \
						$(DOC_DEFAULT_HTML_LIST))

CLEAN_FORMAT_SOURCES_LIST=		$(addprefix \
						$(CLEAN_PREFIX)_, \
						$(FORMAT_SOURCES_EXISTING_LIST))

CLEAN_DOC_DEFAULT_HTML_LIST=		$(addprefix \
						$(CLEAN_PREFIX)_, \
						$(DOC_DEFAULT_HTML_LIST))

endif

