ifndef MK_CLEAN_DEEP_MK
MK_CLEAN_DEEP_MK=			TRUE

INCLUDER_MODULES_LIST=			config \
					clean

ifndef INCLUDER_PATH
$(error tool modbuild is not installed in your build system!)
else
include $(INCLUDER_PATH)
endif

CLEAN_DEEP_PREFIX=			$(CONFIG_CLEAN_DEEP_RULE)

CLEAN_DEEP_APPLICATIONS_PREFIX=		$(CLEAN_DEEP_PREFIX)_$(CONFIG_APPLICATION_PREFIX)
CLEAN_DEEP_MODULES_PREFIX=		$(CLEAN_DEEP_PREFIX)_$(CONFIG_MODULE_PREFIX)
CLEAN_DEEP_TOOLS_PREFIX=		$(CLEAN_DEEP_PREFIX)_$(CONFIG_TOOL_PREFIX)

CLEAN_DEEP_APPLICATIONS_PLATFORMS_STANDARD_LIST=	$(patsubst \
								$(CONFIG_CLEAN_RULE)_%, \
								$(CONFIG_CLEAN_DEEP_RULE)_%, \
								$(CLEAN_APPLICATIONS_PLATFORMS_STANDARD_LIST))

CLEAN_DEEP_APPLICATIONS_PLATFORMS_NONSTANDARD_LIST=	$(patsubst \
								$(CONFIG_CLEAN_RULE)_%, \
								$(CONFIG_CLEAN_DEEP_RULE)_%, \
								$(CLEAN_APPLICATIONS_PLATFORMS_NONSTANDARD_LIST))

CLEAN_DEEP_MODULES_PLATFORMS_STANDARD_LIST=	$(patsubst \
							$(CONFIG_CLEAN_RULE)_%, \
							$(CONFIG_CLEAN_DEEP_RULE)_%, \
							$(CLEAN_MODULES_PLATFORMS_STANDARD_LIST))

CLEAN_DEEP_MODULES_PLATFORMS_NONSTANDARD_LIST=	$(patsubst \
							$(CONFIG_CLEAN_RULE)_%, \
							$(CONFIG_CLEAN_DEEP_RULE)_%, \
							$(CLEAN_MODULES_PLATFORMS_NONSTANDARD_LIST))

CLEAN_DEEP_TOOLS_PLATFORMS_STANDARD_LIST=	$(patsubst \
							$(CONFIG_CLEAN_RULE)_%, \
							$(CONFIG_CLEAN_DEEP_RULE)_%, \
							$(CLEAN_TOOLS_PLATFORMS_STANDARD_LIST))

CLEAN_DEEP_TOOLS_PLATFORMS_NONSTANDARD_LIST=	$(patsubst \
							$(CONFIG_CLEAN_RULE)_%, \
							$(CONFIG_CLEAN_DEEP_RULE)_%, \
							$(CLEAN_TOOLS_PLATFORMS_NONSTANDARD_LIST))

endif

