ifndef MK_COVERAGE_MK
MK_COVERAGE_MK=			TRUE

INCLUDER_MODULES_LIST=		config \
				name \
				dirs \
				sources/c

ifndef INCLUDER_PATH
$(error tool modbuild is not installed in your build system!)
else
include $(INCLUDER_PATH)
endif

# TODO: Implement rules for gcno and gcda files.
COVERAGE_GCOV_DIR_NAME=		$(CONFIG_GCOV_FILE_EXT)
COVERAGE_LCOV_DIR_NAME=		$(CONFIG_LCOV_FILE_EXT)
COVERAGE_HTML_DIR_NAME=		$(CONFIG_HTML_FILE_EXT)

COVERAGE_PLATFORM_DIR=		$(DIRS_COVERAGE_DIR)/$(PLATFORM)

COVERAGE_GCOV_PLATFORM_DIR=	$(COVERAGE_PLATFORM_DIR)/$(COVERAGE_GCOV_DIR_NAME)
COVERAGE_LCOV_PLATFORM_DIR=	$(COVERAGE_PLATFORM_DIR)/$(COVERAGE_LCOV_DIR_NAME)
COVERAGE_HTML_PLATFORM_DIR=	$(COVERAGE_PLATFORM_DIR)/$(COVERAGE_HTML_DIR_NAME)

COVERAGE_GCOV_C_LIST=		$(patsubst \
					$(DIRS_SOURCES_DIR)/%, \
					$(COVERAGE_GCOV_PLATFORM_DIR)/%.$(CONFIG_GCOV_FILE_EXT), \
					$(SOURCES_C_LIST))

COVERAGE_GCDA_C_LIST=		$(patsubst \
					$(DIRS_SOURCES_DIR)/%.$(CONFIG_C_SOURCE_FILE_EXT), \
					$(DIRS_OBJECTS_DIR)/$(PLATFORM)/%_$(SIGNATURE_SUFFIX).gcda, \
					$(SOURCES_C_LIST))

# TODO: This code is present in includes.mk, libs.mk and coverage.mk - merge it!
COVERAGE_DEPENDENCIES_EXISTENCE=	$(wildcard \
					$(CONFIG_MODULE_DEP_FILE_NAME))

ifneq ($(COVERAGE_DEPENDENCIES_EXISTENCE), )
COVERAGE_DEPENDENCIES_COMMAND=	cat \
					$(CONFIG_MODULE_DEP_FILE_NAME)

COVERAGE_MODULES_LIST=		$(shell \
					$(COVERAGE_DEPENDENCIES_COMMAND))
else
COVERAGE_MODULES_LIST=
endif

# TODO: Put into platform directory
COVERAGE_APPLICATION_PREFIX=	$(COVERAGE_LCOV_PLATFORM_DIR)/$(CONFIG_APPLICATION_PREFIX)
COVERAGE_MODULE_PREFIX=		$(COVERAGE_LCOV_PLATFORM_DIR)/$(CONFIG_MODULE_PREFIX)

COVERAGE_APPLICATION_FILE=	$(COVERAGE_APPLICATION_PREFIX)_$(NAME).$(CONFIG_LCOV_FILE_EXT)

COVERAGE_MODULE_FILE_LIST=	$(patsubst \
					%, \
					$(COVERAGE_MODULE_PREFIX)_%.$(CONFIG_LCOV_FILE_EXT), \
					$(COVERAGE_MODULES_LIST))

endif

