ifndef MK_DEPENDENCIES_MK
MK_DEPENDENCIES_MK=		TRUE

INCLUDER_MODULES_LIST=		dirs \
				config \
				signature

ifndef INCLUDER_PATH
$(error tool modbuild is not installed in your build system!)
else
include $(INCLUDER_PATH)
endif

DEPENDENCIES_FILE=		$(DIRS_BS_TEMP_DIR)/$(CONFIG_DEPENDENCIES_FILE_NAME)
DEPENDENCIES_APPLICATION_NAME=	smart_deps
DEPENDENCIES_APPLICATION_DIR=	$(DIRS_TOOLS_DIR)/$(DEPENDENCIES_APPLICATION_NAME)/$(DIRS_INSTALL_DIR)/$(PLATFORM_HOST_ARCHITECTURE)
DEPENDENCIES_APPLICATION_PATH=	$(DEPENDENCIES_APPLICATION_DIR)/$(DEPENDENCIES_APPLICATION_NAME)

ifneq ($(wildcard $(DEPENDENCIES_FILE)), )
$(CONFIG_ALL_RULE): \
	$(DEPENDENCIES_FILE)
endif

.PHONY: \
		$(DEPENDENCIES_FILE)

ifneq ($(wildcard $(DEPENDENCIES_APPLICATION_PATH)), )
$(DEPENDENCIES_FILE): \
		$(DIRS_BS_TEMP_DIR)
	./$(DEPENDENCIES_APPLICATION_PATH) > \
	$@
else
$(DEPENDENCIES_FILE):
endif

include $(DEPENDENCIES_FILE)

endif

