ifndef MK_DEPENDENCIES_MK
MK_DEPENDENCIES_MK=		TRUE

INCLUDER_MODULES_LIST=		dirs \
				config

ifndef INCLUDER_PATH
$(error tool modbuild is not installed in your build system!)
else
include $(INCLUDER_PATH)
endif

DEPENDENCIES_FILE=		$(DIRS_BS_TEMP_DIR)/$(CONFIG_DEPENDENCIES_FILE_NAME)
DEPENDENCIES_APPLICATION_NAME=	smart_deps

$(DEPENDENCIES_FILE): | \
		$(DIRS_BS_TEMP_DIR)
	$(DEPENDENCIES_APPLICATION_NAME) > \
	$@

include $(DEPENDENCIES_FILE)

endif

