ifndef MK_DEPLOY_MK
MK_DEPLOY_MK=				TRUE

INCLUDER_MODULES_LIST=			config \
					dirs \
					tools

ifndef INCLUDER_PATH
$(error tool modbuild is not installed in your build system!)
else
include $(INCLUDER_PATH)
endif

DEPLOY_PREFIX=				$(CONFIG_DEPLOY_RULE)

DEPLOY_APPLICATION_PREFIX=		$(DEPLOY_PREFIX)_$(CONFIG_APPLICATION_PREFIX)
DEPLOY_MODULE_PREFIX=			$(DEPLOY_PREFIX)_$(CONFIG_MODULE_PREFIX)
DEPLOY_TOOL_PREFIX=			$(DEPLOY_PREFIX)_$(CONFIG_TOOL_PREFIX)

DEPLOY_TOOLS_COMMAND=			find \
						$(DIRS_TOOLS_DIR) \
						-type \
						l \
						-name \
						$(CONFIG_DEPLOY_DNS_FILE_NAME)

DEPLOY_TOOLS_FILE_LIST=			$(shell \
						$(DEPLOY_TOOLS_COMMAND))

DEPLOY_TOOLS_BARE_FOUND_LIST=		$(patsubst \
						$(DIRS_TOOLS_DIR)/%/$(CONFIG_DEPLOY_DNS_FILE_NAME), \
						%, \
						$(DEPLOY_TOOLS_FILE_LIST))

DEPLOY_TOOLS_FOUND_LIST=		$(patsubst \
						%, \
						$(CONFIG_TOOL_PREFIX)_%-%, \
						$(DEPLOY_TOOLS_BARE_FOUND_LIST))

DEPLOY_TOOLS_BARE_STANDARD_LIST=	$(filter \
						$(DEPLOY_TOOLS_FOUND_LIST), \
						$(TOOLS_PLATFORMS_STANDARD_LIST))

DEPLOY_TOOLS_BARE_NONSTANDARD_LIST=	$(filter \
						$(DEPLOY_TOOLS_FOUND_LIST), \
						$(TOOLS_PLATFORMS_NONSTANDARD_LIST))

DEPLOY_TOOLS_PLATFORMS_STANDARD_LIST=	$(addprefix \
						$(DEPLOY_PREFIX)_, \
						$(DEPLOY_TOOLS_BARE_STANDARD_LIST))

DEPLOY_TOOLS_PLATFORMS_NONSTANDARD_LIST=	$(addprefix \
							$(DEPLOY_PREFIX)_, \
							$(DEPLOY_TOOLS_BARE_NONSTANDARD_LIST))

endif

