ifndef MK_DEPLOY_MK
MK_DEPLOY_MK=				TRUE

INCLUDER_MODULES_LIST=			config \
					dirs \
					tools \
					pacman \
					relative

ifndef INCLUDER_PATH
$(error tool modbuild is not installed in your build system!)
else
include $(INCLUDER_PATH)
endif

DEPLOY_PREFIX=				$(CONFIG_DEPLOY_RULE)

DEPLOY_APPLICATION_PREFIX=		$(DEPLOY_PREFIX)_$(CONFIG_APPLICATION_PREFIX)
DEPLOY_MODULE_PREFIX=			$(DEPLOY_PREFIX)_$(CONFIG_MODULE_PREFIX)
DEPLOY_TOOL_PREFIX=			$(DEPLOY_PREFIX)_$(CONFIG_TOOL_PREFIX)

DEPLOY_TOOLS_COMMAND=			find \
						$(DIRS_TOOLS_DIR) \
						-type \
						l \
						-name \
						$(CONFIG_DEPLOY_DNS_FILE_NAME)

DEPLOY_TOOLS_FILE_LIST=			$(shell \
						$(DEPLOY_TOOLS_COMMAND))

DEPLOY_TOOLS_BARE_FOUND_LIST=		$(patsubst \
						$(DIRS_TOOLS_DIR)/%/$(CONFIG_DEPLOY_DNS_FILE_NAME), \
						%, \
						$(DEPLOY_TOOLS_FILE_LIST))

DEPLOY_TOOLS_FOUND_LIST=		$(patsubst \
						%, \
						$(CONFIG_TOOL_PREFIX)_%-%, \
						$(DEPLOY_TOOLS_BARE_FOUND_LIST))

DEPLOY_TOOLS_BARE_STANDARD_LIST=	$(filter \
						$(DEPLOY_TOOLS_FOUND_LIST), \
						$(TOOLS_PLATFORMS_STANDARD_LIST))

DEPLOY_TOOLS_BARE_NONSTANDARD_LIST=	$(filter \
						$(DEPLOY_TOOLS_FOUND_LIST), \
						$(TOOLS_PLATFORMS_NONSTANDARD_LIST))

DEPLOY_TOOLS_PLATFORMS_STANDARD_LIST=	$(addprefix \
						$(DEPLOY_PREFIX)_, \
						$(DEPLOY_TOOLS_BARE_STANDARD_LIST))

DEPLOY_TOOLS_PLATFORMS_NONSTANDARD_LIST=	$(addprefix \
							$(DEPLOY_PREFIX)_, \
							$(DEPLOY_TOOLS_BARE_NONSTANDARD_LIST))

DEPLOY_CI_USERNAME_FILE=		$(DIRS_CI_DIR)/$(CONFIG_DEPLOY_USERNAME_FILE_NAME)

DEPLOY_RELATIVE_CI_USERNAME_FILE=	$(RELATIVE_ROOT_DIR)/$(DEPLOY_CI_USERNAME_FILE)

DEPLOY_REMOTE_USER_NAME_COMMAND=	cat \
						$(DEPLOY_RELATIVE_CI_USERNAME_FILE)

ifneq ($(wildcard $(DEPLOY_RELATIVE_CI_USERNAME_FILE)), )
DEPLOY_REMOTE_USER_NAME=		$(shell \
						$(DEPLOY_REMOTE_USER_NAME_COMMAND))
else
DEPLOY_REMOTE_USER_NAME=		root
endif

DEPLOY_REMOTE_USER_NAME_EMPTY_MESSAGE=	Remote \
					username \
					is \
					set \
					to \
					empty \
					value \
					in \
					file \
					$(DEPLOY_CI_USERNAME_FILE)

ifeq ($(DEPLOY_REMOTE_USER_NAME), )
$(error $(DEPLOY_REMOTE_USER_NAME_EMPTY_MESSAGE))
endif

# TODO: Move this name to .circleci directory to repo.name file.
# TODO: This value should be dependent to project.
DEPLOY_REPO_BASE_NAME=			archipelagos

DEPLOY_COPY_DONE_FILE_NAME_COMMAND=	cat \
						$(CONFIG_DEPLOY_DNS_FILE_NAME)

DEPLOY_REMOTE_HOST_NAME=		$(shell \
						$(DEPLOY_COPY_DONE_FILE_NAME_COMMAND))

DEPLOY_REMOTE_USER_AT_HOST=		$(DEPLOY_REMOTE_USER_NAME)@$(DEPLOY_REMOTE_HOST_NAME)

DEPLOY_REMOTE_REPO_ABS_DIR=		/srv/http/archlinux/$(DEPLOY_REPO_BASE_NAME)/os/x86_64

DEPLOY_PACMAN_ARCHIVE_FILE_NAME=	$(SIGNATURE_TOOL_FILE_NAME)-$(PACMAN_ARCHIVE_VERSION)-$(PACMAN_ARCHIVE_RELEASE)-$(PACMAN_ARCHIVE_ARCH).$(PACMAN_EXT)

DEPLOY_PACMAN_ARCHIVE_FILE=		$(DEPLOY_REMOTE_REPO_ABS_DIR)/$(DEPLOY_PACMAN_ARCHIVE_FILE_NAME)
DEPLOY_PACMAN_ARCHIVE_OLD_FILE=		$(DEPLOY_REMOTE_REPO_ABS_DIR)/$(SIGNATURE_TOOL_FILE_NAME)-\*

DEPLOY_REPO_FILE_NAME=			$(DEPLOY_REPO_BASE_NAME).$(CONFIG_REPO_EXT)

DEPLOY_REMOTE_REPO_FILE=		$(DEPLOY_REMOTE_REPO_ABS_DIR)/$(DEPLOY_REPO_FILE_NAME)

DEPLOY_ADD_REMOTE_HOST_FLAG=		-o \
					StrictHostKeyChecking=no

DEPLOY_CI_PEM_FILE=			$(DIRS_CI_DIR)/$(CONFIG_DEPLOY_PEM_FILE_NAME)

DEPLOY_RELATIVE_CI_PEM_FILE=		$(RELATIVE_ROOT_DIR)/$(DEPLOY_CI_PEM_FILE)

ifneq ($(wildcard $(DEPLOY_RELATIVE_CI_PEM_FILE)), )
DEPLOY_PEM_FILE_FLAG=			-i \
					$(DEPLOY_RELATIVE_CI_PEM_FILE)
else
DEPLOY_PEM_FILE_FLAG=
endif

DEPLOY_SSH_INIT_COMMAND=		ssh \
						$(DEPLOY_PEM_FILE_FLAG) \
						$(DEPLOY_ADD_REMOTE_HOST_FLAG) \
						$(DEPLOY_REMOTE_USER_AT_HOST) \
						true

DEPLOY_SSH_MKDIR_REPO_COMMAND=		ssh \
						$(DEPLOY_PEM_FILE_FLAG) \
						$(DEPLOY_REMOTE_USER_AT_HOST) \
						mkdir \
						-p \
						$(DEPLOY_REMOTE_REPO_ABS_DIR)

DEPLOY_SSH_TOUCH_REPO_COMMAND=		ssh \
						$(DEPLOY_PEM_FILE_FLAG) \
						$(DEPLOY_REMOTE_USER_AT_HOST) \
						touch \
						$(DEPLOY_REMOTE_REPO_FILE)

DEPLOY_SSH_REMOVE_FROM_REPO_COMMAND=	ssh \
						$(DEPLOY_PEM_FILE_FLAG) \
						$(DEPLOY_REMOTE_USER_AT_HOST) \
						repo-remove \
						$(DEPLOY_REMOTE_REPO_FILE) \
						$(SIGNATURE_TOOL_FILE_NAME)

DEPLOY_SSH_REMOVE_FILE_COMMAND=		ssh \
						$(DEPLOY_PEM_FILE_FLAG) \
						$(DEPLOY_REMOTE_USER_AT_HOST) \
						rm \
						-f \
						$(DEPLOY_PACMAN_ARCHIVE_OLD_FILE)

DEPLOY_SCP_PACMAN_ARCHIVE_COMMAND=	scp \
						$(DEPLOY_PEM_FILE_FLAG) \
						$(PACMAN_PLATFORM_DIR)/$(DEPLOY_PACMAN_ARCHIVE_FILE_NAME) \
						$(DEPLOY_REMOTE_USER_AT_HOST):$(DEPLOY_PACMAN_ARCHIVE_FILE)

DEPLOY_SSH_ADD_TO_REPO_COMMAND=		ssh \
						$(DEPLOY_PEM_FILE_FLAG) \
						$(DEPLOY_REMOTE_USER_AT_HOST) \
						repo-add \
						$(DEPLOY_REMOTE_REPO_FILE) \
						$(DEPLOY_PACMAN_ARCHIVE_FILE)

endif

