ifndef MK_DIRS_MK
MK_DIRS_MK=			TRUE

INCLUDER_MODULES_LIST=		config

DIRS_APPLICATIONS_DIR=		$(CONFIG_APPLICATION_PREFIX)s
DIRS_MODULES_DIR=		$(CONFIG_MODULE_PREFIX)s
DIRS_TOOLS_DIR=			$(CONFIG_TOOL_PREFIX)s

DIRS_MK_DIR=			bs
DIRS_TEMP_DIR=			tmp
DIRS_BS_TEMP_DIR=		$(DIRS_MK_DIR)/$(DIRS_TEMP_DIR)
DIRS_TEMPLATES_DIR=		$(DIRS_MK_DIR)/templates

DIRS_BIN_DIR=			bin
DIRS_SOURCES_DIR=		src
DIRS_INCLUDE_DIR=		include
DIRS_LINKER_DIR=		$(CONFIG_LD_EXT)

DIRS_GDB_DIR=			gdb

DIRS_DOWNLOAD_DIR=		download
DIRS_OBJECTS_DIR=		obj
DIRS_CTAGS_DIR=			ctags
DIRS_UNIT_TEST_DIR=		unit_test
DIRS_DOC_DIR=			doc
DIRS_DEP_DIR=			$(CONFIG_DEP_EXT)s
DIRS_MAP_DIR=			$(CONFIG_MAP_EXT)
DIRS_AUX_DIR=			$(CONFIG_AUX_EXT)
DIRS_PNG_DIR=			$(CONFIG_PNG_FILE_EXT)
DIRS_LIB_DIR=			lib
DIRS_COVERAGE_DIR=		coverage
DIRS_INSTALL_DIR=		install
DIRS_PACMAN_DIR=		pacman
DIRS_CI_DIR=			.circleci

DIRS_PULL_DIR=			pull
DIRS_PUSH_DIR=			push

endif

