ifndef MK_DOC_MK
MK_DOC_MK=			TRUE

INCLUDER_MODULES_LIST=		config \
				doc/png

ifndef INCLUDER_PATH
$(error tool modbuild is not installed in your build system!)
else
include $(INCLUDER_PATH)
endif

DOC_PREFIX=				$(CONFIG_DOC_RULE)

DOC_APP_PREFIX=				$(DOC_PREFIX)_$(CONFIG_APPLICATION_PREFIX)
DOC_MOD_PREFIX=				$(DOC_PREFIX)_$(CONFIG_MODULE_PREFIX)

DOC_APP_STANDARD_LIST=			$(patsubst \
						$(CONFIG_APPLICATION_PREFIX)_%, \
						$(DOC_APP_PREFIX)_%, \
						$(APPLICATIONS_PLATFORMS_STANDARD_LIST))


DOC_APP_NONSTANDARD_LIST=		$(patsubst \
						$(CONFIG_APPLICATION_PREFIX)_%, \
						$(DOC_APP_PREFIX)_%, \
						$(APPLICATIONS_PLATFORMS_NONSTANDARD_LIST))

DOC_MOD_STANDARD_LIST=			$(patsubst \
						$(CONFIG_MODULE_PREFIX)_%, \
						$(DOC_MOD_PREFIX)_%, \
						$(MODULES_PLATFORMS_STANDARD_LIST))


DOC_MOD_NONSTANDARD_LIST=		$(patsubst \
						$(CONFIG_MODULE_PREFIX)_%, \
						$(DOC_MOD_PREFIX)_%, \
						$(MODULES_PLATFORMS_NONSTANDARD_LIST))

# TODO: Should be moved to config.
DOC_README_ASCIIDOC_FILE=		README.$(CONFIG_ASCIIDOC_FILE_EXT)
DOC_TODO_ASCIIDOC_FILE=			TODO.$(CONFIG_ASCIIDOC_FILE_EXT)

DOC_DEFAULT_ASCIIDOC_LIST=

ifneq ($(wildcard $(DOC_README_ASCIIDOC_FILE)), )
DOC_DEFAULT_ASCIIDOC_LIST+=		$(DOC_README_ASCIIDOC_FILE)
endif

ifneq ($(wildcard $(DOC_TODO_ASCIIDOC_FILE)), )
DOC_DEFAULT_ASCIIDOC_LIST+=		$(DOC_TODO_ASCIIDOC_FILE)
endif

DOC_DEFAULT_HTML_LIST=			$(patsubst \
						%.$(CONFIG_ASCIIDOC_FILE_EXT), \
						%.$(CONFIG_HTML_FILE_EXT), \
						$(DOC_DEFAULT_ASCIIDOC_LIST))

endif

