ifndef MK_DOWNLOAD_MK
MK_DOWNLOAD_MK=			TRUE

INCLUDER_MODULES_LIST=		dirs \
				config \
				launcher \
				flags_make

ifndef INCLUDER_PATH
$(error aosmake package is not installed in your OS!)
else
include $(INCLUDER_PATH)
endif

# TODO: This file should be set in config.mk, and rules file should be moved into templates.
DOWNLOAD_REPOSITORY_URL_COMMAND=	cat \
						$(CONFIG_DOWNLOAD_FILE_NAME)

# TODO: Make guard and check if url exists!
DOWNLOAD_REPOSITORY_URL=	$(shell \
					$(DOWNLOAD_REPOSITORY_URL_COMMAND))

# TODO: Try to find template file in more smart way.
ifneq ($(wildcard $(CONFIG_DOWNLOAD_FILE_NAME)), )
DOWNLOAD_ALL=			make \
					DIRS_DOWNLOAD_DIR=$(DIRS_DOWNLOAD_DIR) \
					CLEAN_PREFIX=$(CLEAN_PREFIX) \
					DOWNLOAD_REPOSITORY_URL=$(DOWNLOAD_REPOSITORY_URL) \
					CLEAN_FULL_PREFIX=$(CLEAN_FULL_PREFIX) \
					$(LAUNCHER_VARIABLES) \
					$(FLAGS_MAKE_LIST) \
					-f \
					../../$(DIRS_TEMPLATES_DIR)/$(CONFIG_DEFAULT_DOWNLOAD_BUILDSCRIPT_FILE_NAME) \
					$(DIRS_DOWNLOAD_DIR)

DOWNLOAD_CLEAN=			make \
					DIRS_DOWNLOAD_DIR=$(DIRS_DOWNLOAD_DIR) \
					CLEAN_PREFIX=$(CLEAN_PREFIX) \
					DOWNLOAD_REPOSITORY_URL=$(DOWNLOAD_REPOSITORY_URL) \
					CLEAN_FULL_PREFIX=$(CLEAN_FULL_PREFIX) \
					$(LAUNCHER_VARIABLES) \
					$(FLAGS_MAKE_LIST) \
					-f \
					../../$(DIRS_TEMPLATES_DIR)/$(CONFIG_DEFAULT_DOWNLOAD_BUILDSCRIPT_FILE_NAME) \
					$(CLEAN_PREFIX)_$(DIRS_DOWNLOAD_DIR)

DOWNLOAD_CLEAN_FULL=		make \
					DIRS_DOWNLOAD_DIR=$(DIRS_DOWNLOAD_DIR) \
					CLEAN_PREFIX=$(CLEAN_PREFIX) \
					DOWNLOAD_REPOSITORY_URL=$(DOWNLOAD_REPOSITORY_URL) \
					CLEAN_FULL_PREFIX=$(CLEAN_FULL_PREFIX) \
					$(LAUNCHER_VARIABLES) \
					$(FLAGS_MAKE_LIST) \
					-f \
					../../$(DIRS_TEMPLATES_DIR)/$(CONFIG_DEFAULT_DOWNLOAD_BUILDSCRIPT_FILE_NAME) \
					$(CLEAN_FULL_PREFIX)_$(DIRS_DOWNLOAD_DIR)
else
DOWNLOAD_ALL=
DOWNLOAD_CLEAN=
endif

endif

