ifndef MK_DOXYGEN_MK
MK_DOXYGEN_MK=				TRUE

INCLUDER_MODULES_LIST=			config \
					modules \
					applications

ifndef INCLUDER_PATH
$(error doxygen package is not installed in your OS!)
else
include $(INCLUDER_PATH)
endif

DOXYGEN_PREFIX=				$(CONFIG_DOXYGEN_RULE)

DOXYGEN_APP_PREFIX=			$(DOXYGEN_PREFIX)_$(CONFIG_APPLICATION_PREFIX)
DOXYGEN_MOD_PREFIX=			$(DOXYGEN_PREFIX)_$(CONFIG_MODULE_PREFIX)

DOXYGEN_APP_STANDARD_LIST=		$(patsubst \
						$(CONFIG_APPLICATION_PREFIX)_%, \
						$(DOXYGEN_APP_PREFIX)_%, \
						$(APPLICATIONS_STANDARD_LIST))

DOXYGEN_APP_NONSTANDARD_LIST=		$(patsubst \
						$(CONFIG_APPLICATION_PREFIX)_%, \
						$(DOXYGEN_APP_PREFIX)_%, \
						$(APPLICATIONS_NONSTANDARD_LIST))

DOXYGEN_MOD_STANDARD_LIST=		$(patsubst \
						$(CONFIG_MODULE_PREFIX)_%, \
						$(DOXYGEN_MOD_PREFIX)_%, \
						$(MODULES_STANDARD_LIST))

DOXYGEN_MOD_NONSTANDARD_LIST=		$(patsubst \
						$(CONFIG_MODULE_PREFIX)_%, \
						$(DOXYGEN_MOD_PREFIX)_%, \
						$(MODULES_NONSTANDARD_LIST))

DOXYGEN_SOURCE_C_EXT_SUFFIX=		$(CONFIG_C_SOURCE_FILE_EXT).$(DOXYGEN_PREFIX)

DOXYGEN_SOURCES_C_LIST=			$(patsubst \
						$(DIRS_SOURCES_DIR)/%.$(CONFIG_C_SOURCE_FILE_EXT), \
						$(DIRS_SOURCES_DIR)/%.$(DOXYGEN_SOURCE_C_EXT_SUFFIX), \
						$(SOURCES_C_LIST))

DOXYGEN_SOURCES_LIST=			$(DOXYGEN_SOURCES_C_LIST)

DOXYGEN_SOURCES_EXISTING_LIST=		$(wildcard \
						$(DOXYGEN_SOURCES_C_LIST))

DOXYGEN_COMMAND=			doxygen

DOXYGEN_CONFIGURATION_FILE_NAME=		$(DOXYGEN_COMMAND).$(CONFIG_CFG_EXT)
DOXYGEN_CONFIGURATION_FILE=		$(ROOT_DIR)/$(DIRS_TEMPLATES_DIR)/$(DOXYGEN_CONFIGURATION_FILE_NAME)

DOXYGEN_FLAGS=				$(DOXYGEN_CONFIGURATION_FILE)

DOXYGEN_DOC_DIR=			doxygen
endif
