ifndef MK_EXEC_MK
MK_EXEC_MK=			TRUE

INCLUDER_MODULES_LIST=		root \
				dirs \
				name \
				signature \
				platform

ifndef INCLUDER_PATH
$(error tool modbuild is not installed in your build system!)
else
include $(INCLUDER_PATH)
endif

EXEC_BASE_LINE=			"======"
EXEC_BEGIN_TEXT=		" BEGIN OF EXECUTION "
EXEC_END_TEXT=			"  END OF EXECUTION  "

EXEC_LINE_LABEL=		$(EXEC_BASE_LINE) \
				$(EXEC_BASE_LINE) \
				$(EXEC_BASE_LINE) \
				$(EXEC_BASE_LINE) \
				$(EXEC_BASE_LINE)

EXEC_BEGIN_LABEL=		$(EXEC_BASE_LINE) \
				$(EXEC_BEGIN_TEXT) \
				$(EXEC_BASE_LINE)

EXEC_END_LABEL=			$(EXEC_BASE_LINE) \
				$(EXEC_END_TEXT) \
				$(EXEC_BASE_LINE)

EXEC_APPLICATION_DIR=		$(ROOT_DIR)/$(DIRS_APPLICATIONS_DIR)/$(NAME)
EXEC_APPLICATION_PATH=		$(EXEC_APPLICATION_DIR)/$(INSTALL_APPLICATION_ELF_FILE)

endif

