ifndef MK_NON_STANDARD_MK
MK_NON_STANDARD_MK=			TRUE

INCLUDER_MODULES_LIST=			dirs

ifndef INCLUDER_PATH
$(error aosmake package is not installed in your OS!)
else
include $(INCLUDER_PATH)
endif

NON_STANDARD_GREP_EXEC_PREFIX=		-e
NON_STANDARD_GREP_IGNORE_PREFIX=	-v

NON_STANDARD_SEARCH_DIRS_LIST=		$(DIRS_APPLICATIONS_DIR) \
					$(DIRS_MODULES_DIR) \
					$(DIRS_TOOLS_DIR)

NON_STANDARD_IGNORE_EXT_BARE_LIST=	h \
					js \
					html \
					css \
					$(CONFIG_ASM_SOURCE_FILE_EXT) \
					$(CONFIG_C_SOURCE_FILE_EXT) \
					$(CONFIG_CPP_SOURCE_FILE_EXT) \
					$(CONFIG_ASM_OBJECT_FILE_EXT) \
					$(CONFIG_C_OBJECT_FILE_EXT) \
					$(CONFIG_CPP_OBJECT_FILE_EXT) \
					$(CONFIG_ASCIIDOC_FILE_EXT) \
					$(CONFIG_DOT_FILE_EXT) \
					$(CONFIG_LD_EXT) \
					$(CONFIG_BUILD_SYSTEM_SCRIPT_EXT) \
					$(CONFIG_DEP_EXT) \
					$(CONFIG_ARGS_EXT) \
					$(CONFIG_LIST_EXT) \
					$(CONFIG_GDB_SCRIPT_EXT) \
					$(CONFIG_GITREPO_EXT)

NON_STANDARD_IGNORE_EXT_LIST=		$(patsubst \
						%, \
						\\.%$$, \
						$(NON_STANDARD_IGNORE_EXT_BARE_LIST))

NON_STANDARD_IGNORE_ALL_BARE_LIST=	$(NON_STANDARD_IGNORE_EXT_LIST) \
					$(CONFIG_MAKEFILE_FILE_NAME)

NON_STANDARD_IGNORE_ALL_LIST=		$(addprefix \
						$(NON_STANDARD_GREP_EXEC_PREFIX), \
						$(NON_STANDARD_IGNORE_ALL_BARE_LIST))

NON_STANDARD_FIND_LIST_COMMAND=		find \
						$(NON_STANDARD_SEARCH_DIRS_LIST) \
						-type \
						f | \
					grep \
						$(NON_STANDARD_GREP_IGNORE_PREFIX) \
						$(NON_STANDARD_IGNORE_ALL_LIST)

endif

