ifndef MK_OR1K_MK
MK_OR1K_MK=			TRUE

INCLUDER_MODULES_LIST=		dirs

ifndef INCLUDER_PATH
$(error tool modbuild is not installed in your build system!)
else
include $(INCLUDER_PATH)
endif

OR1K_TOOLCHAIN_NEWLIB_PREFIX=	or1k-elf
OR1K_TOOLCHAIN_UCLIBC_PREFIX=	or1k-linux-uclibc

OR1K_TOOLCHAIN_NEWLIB_NAME=	or1k_toolchain_newlib
OR1K_TOOLCHAIN_UCLIBC_NAME=	or1k_toolchain_uclibc

OR1K_TOOLCHAIN_NEWLIB_BASE_PATH=	$(DIRS_TOOLS_DIR)/$(OR1K_TOOLCHAIN_NEWLIB_NAME)
OR1K_TOOLCHAIN_UCLIBC_BASE_PATH=	$(DIRS_TOOLS_DIR)/$(OR1K_TOOLCHAIN_UCLIBC_NAME)

OR1K_TOOLCHAIN_NEWLIB_PATH=	$(RELATIVE_ROOT_DIR)/$(OR1K_TOOLCHAIN_NEWLIB_BASE_PATH)
OR1K_TOOLCHAIN_UCLIBC_PATH=	$(RELATIVE_ROOT_DIR)/$(OR1K_TOOLCHAIN_UCLIBC_BASE_PATH)

OR1K_TOOLCHAIN_NEWLIB_ABS_PATH=	$(realpath \
					$(OR1K_TOOLCHAIN_NEWLIB_PATH))

OR1K_TOOLCHAIN_UCLIBC_ABS_PATH=	$(realpath \
					$(OR1K_TOOLCHAIN_UCLIBC_PATH))

OR1K_TOOLCHAIN_SYSROOT_DIR_NAME=	sys-root
OR1K_TOOLCHAIN_SYSROOT_DIR=	$(OR1K_TOOLCHAIN_UCLIBC_ABS_PATH)/$(DIRS_INSTALL_DIR)/$(OR1K_TOOLCHAIN_SYSROOT_DIR_NAME)

OR1K_BINUTILS_REPOSITORY_URL=	http://github.com/openrisc/or1k-src
OR1K_GCC_REPOSITORY_URL=	http://github.com/openrisc/or1k-gcc

OR1K_NEWLIB_REPOSITORY_URL=	http://github.com/openrisc/newlib
OR1K_UCLIBC_REPOSITORY_URL=	http://github.com/openrisc/uClibc-or1k
OR1K_OR1KSIM_REPOSITORY_URL=	http://github.com/openrisc/or1ksim
OR1K_OPENOCD_REPOSITORY_URL=	http://github.com/openrisc/openOCD

OR1K_LINUX__REPOSITORY_URL=	http://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux

endif

