ifndef MK_REBUILD_DEEP_MK
MK_REBUILD_DEEP_MK=				TRUE

INCLUDER_MODULES_LIST=				config \
						rebuild

ifndef INCLUDER_PATH
$(error tool modbuild is not installed in your build system!)
else
include $(INCLUDER_PATH)
endif

REBUILD_DEEP_PREFIX=				$(CONFIG_REBUILD_DEEP_RULE)

REBUILD_DEEP_APPLICATION_PREFIX=		$(REBUILD_DEEP_PREFIX)_$(CONFIG_APPLICATION_PREFIX)
REBUILD_DEEP_MODULE_PREFIX=			$(REBUILD_DEEP_PREFIX)_$(CONFIG_MODULE_PREFIX)
REBUILD_DEEP_TOOL_PREFIX=			$(REBUILD_DEEP_PREFIX)_$(CONFIG_TOOL_PREFIX)

REBUILD_DEEP_APPLICATIONS_PLATFORMS_LIST=	$(patsubst \
							$(REBUILD_PREFIX)_%, \
							$(REBUILD_DEEP_PREFIX)_%, \
							$(REBUILD_APPLICATIONS_PLATFORMS_LIST))

REBUILD_DEEP_MODULES_PLATFORMS_LIST=		$(patsubst \
							$(REBUILD_PREFIX)_%, \
							$(REBUILD_DEEP_PREFIX)_%, \
							$(REBUILD_MODULES_PLATFORMS_LIST))

REBUILD_DEEP_TOOLS_PLATFORMS_LIST=		$(patsubst \
							$(REBUILD_PREFIX)_%, \
							$(REBUILD_DEEP_PREFIX)_%, \
							$(REBUILD_TOOLS_PLATFORMS_LIST))

endif

