ifndef MK_REBUILD_FULL_MK
MK_REBUILD_FULL_MK=				TRUE

INCLUDER_MODULES_LIST=				config \
						rebuild

ifndef INCLUDER_PATH
$(error tool modbuild is not installed in your build system!)
else
include $(INCLUDER_PATH)
endif

REBUILD_FULL_PREFIX=				$(CONFIG_REBUILD_FULL_RULE)

REBUILD_FULL_APPLICATION_PREFIX=		$(REBUILD_FULL_PREFIX)_$(CONFIG_APPLICATION_PREFIX)
REBUILD_FULL_MODULE_PREFIX=			$(REBUILD_FULL_PREFIX)_$(CONFIG_MODULE_PREFIX)
REBUILD_FULL_TOOL_PREFIX=			$(REBUILD_FULL_PREFIX)_$(CONFIG_TOOL_PREFIX)

REBUILD_FULL_APPLICATIONS_PLATFORMS_LIST=	$(patsubst \
							$(REBUILD_PREFIX)_%, \
							$(REBUILD_FULL_PREFIX)_%, \
							$(REBUILD_APPLICATIONS_PLATFORMS_LIST))

REBUILD_FULL_MODULES_PLATFORMS_LIST=		$(patsubst \
							$(REBUILD_PREFIX)_%, \
							$(REBUILD_FULL_PREFIX)_%, \
							$(REBUILD_MODULES_PLATFORMS_LIST))

REBUILD_FULL_TOOLS_PLATFORMS_LIST=		$(patsubst \
							$(REBUILD_PREFIX)_%, \
							$(REBUILD_FULL_PREFIX)_%, \
							$(REBUILD_TOOLS_PLATFORMS_LIST))

endif

