ifndef MK_SELF_TEST_MK
MK_SELF_TEST_MK=			TRUE

INCLUDER_MODULES_LIST=			dirs \
					config \
					modules \
					applications

ifndef INCLUDER_PATH
$(error aosmake package is not installed in your OS!)
else
include $(INCLUDER_PATH)
endif

SELF_TEST_APPLICATIONS_SUFFIX=		$(CONFIG_APPLICATION_PREFIX)s
SELF_TEST_MODULES_SUFFIX=		$(CONFIG_MODULE_PREFIX)s
SELF_TEST_TOOLS_SUFFIX=			$(CONFIG_TOOL_PREFIX)s

# INFO: 
SELF_TEST_PREFIX=			$(CONFIG_SELF_TEST_RULE)
SELF_TEST_DEEP_PREFIX=			$(CONFIG_SELF_TEST_DEEP_RULE)
SELF_TEST_FULL_PREFIX=			$(CONFIG_SELF_TEST_FULL_RULE)

# INFO: 
SELF_TEST_APPLICATIONS_RULE=		$(SELF_TEST_PREFIX)_$(SELF_TEST_APPLICATIONS_SUFFIX)
SELF_TEST_APPLICATIONS_DEEP_RULE=	$(SELF_TEST_DEEP_PREFIX)_$(SELF_TEST_APPLICATIONS_SUFFIX)
SELF_TEST_APPLICATIONS_FULL_RULE=	$(SELF_TEST_FULL_PREFIX)_$(SELF_TEST_APPLICATIONS_SUFFIX)

# INFO: 
SELF_TEST_MODULES_RULE=			$(SELF_TEST_PREFIX)_$(SELF_TEST_MODULES_SUFFIX)
SELF_TEST_MODULES_DEEP_RULE=		$(SELF_TEST_DEEP_PREFIX)_$(SELF_TEST_MODULES_SUFFIX)
SELF_TEST_MODULES_FULL_RULE=		$(SELF_TEST_FULL_PREFIX)_$(SELF_TEST_MODULES_SUFFIX)

# INFO: 
SELF_TEST_TOOLS_RULE=			$(SELF_TEST_PREFIX)_$(SELF_TEST_TOOLS_SUFFIX)
SELF_TEST_TOOLS_DEEP_RULE=		$(SELF_TEST_DEEP_PREFIX)_$(SELF_TEST_TOOLS_SUFFIX)
SELF_TEST_TOOLS_FULL_RULE=		$(SELF_TEST_FULL_PREFIX)_$(SELF_TEST_TOOLS_SUFFIX)

SELF_TEST_LOOP_FIRST_FORMATER=		\ %s\\n\\t\\t%s_%s\\n\\n
SELF_TEST_LOOP_SECOND_FORMATER=		%s_%s:\ \\\\\\n\\t\\t%s\\n
SELF_TEST_LOOP_THIRD_FORMATER=		\\t%s\\n\\t\\t%s\\n
SELF_TEST_LOOP_CONDITION_FORMATER=	\\t%s\\n\\t\\t%s\\n\\t\\t%s\\n\\t%s\\n
SELF_TEST_LOOP_LOG_FORMATER=		\\t%s\\n\\t\\t%s\\n\\t\\t%s\\n\\n
SELF_TEST_LOOP_LAST_FORMATER=		%s_%s:

SELF_TEST_RULE_FIRST_FORMATER=		%s\\n\\t\\t%s\\n
SELF_TEST_RULE_SECOND_FORMATER=		\\t%s\\n\\t\\t%s\\n\\n

SELF_TEST_BASE_FORMATER=		%s

SELF_TEST_EOF_APPLICATIONS_FORMATER=	\ \\\\\\n\\t\\t%s\\n\\n
SELF_TEST_EOF_MODULES_FORMATER=		\ \\\\\\n\\t\\t%s\\n\\n
SELF_TEST_RM_LOG_FORMATER=		\\n\\t%s\\n\\t\\t%s\\n\\t\\t%s\\n

SELF_TEST_GREP_MATCH_PATTERN=		\^\\t''\\t$$*
SELF_TEST_GREP_FLAGS=			-m \
					1 \
					-P

# INFO: 
SELF_TEST_FILE_NAME=			$(SELF_TEST_PREFIX).$(CONFIG_BUILD_SYSTEM_SCRIPT_EXT)
SELF_TEST_DEEP_FILE_NAME=		$(SELF_TEST_DEEP_PREFIX).$(CONFIG_BUILD_SYSTEM_SCRIPT_EXT)
SELF_TEST_FULL_FILE_NAME=		$(SELF_TEST_FULL_PREFIX).$(CONFIG_BUILD_SYSTEM_SCRIPT_EXT)

# INFO: 
SELF_TEST_APPLICATIONS_FILE_NAME=	$(SELF_TEST_APPLICATIONS_RULE).$(CONFIG_BUILD_SYSTEM_SCRIPT_EXT)
SELF_TEST_APPLICATIONS_DEEP_FILE_NAME=	$(SELF_TEST_APPLICATIONS_DEEP_RULE).$(CONFIG_BUILD_SYSTEM_SCRIPT_EXT)
SELF_TEST_APPLICATIONS_FULL_FILE_NAME=	$(SELF_TEST_APPLICATIONS_FULL_RULE).$(CONFIG_BUILD_SYSTEM_SCRIPT_EXT)

# INFO: 
SELF_TEST_MODULES_FILE_NAME=		$(SELF_TEST_MODULES_RULE).$(CONFIG_BUILD_SYSTEM_SCRIPT_EXT)
SELF_TEST_MODULES_DEEP_FILE_NAME=	$(SELF_TEST_MODULES_DEEP_RULE).$(CONFIG_BUILD_SYSTEM_SCRIPT_EXT)
SELF_TEST_MODULES_FULL_FILE_NAME=	$(SELF_TEST_MODULES_FULL_RULE).$(CONFIG_BUILD_SYSTEM_SCRIPT_EXT)

# INFO: 
SELF_TEST_TOOLS_FILE_NAME=		$(SELF_TEST_TOOLS_RULE).$(CONFIG_BUILD_SYSTEM_SCRIPT_EXT)
SELF_TEST_TOOLS_DEEP_FILE_NAME=		$(SELF_TEST_TOOLS_DEEP_RULE).$(CONFIG_BUILD_SYSTEM_SCRIPT_EXT)
SELF_TEST_TOOLS_FULL_FILE_NAME=		$(SELF_TEST_TOOLS_FULL_RULE).$(CONFIG_BUILD_SYSTEM_SCRIPT_EXT)

# INFO: 
SELF_TEST_FILE=				$(DIRS_BS_TEMP_DIR)/$(SELF_TEST_FILE_NAME)
SELF_TEST_DEEP_FILE=			$(DIRS_BS_TEMP_DIR)/$(SELF_TEST_DEEP_FILE_NAME)
SELF_TEST_FULL_FILE=			$(DIRS_BS_TEMP_DIR)/$(SELF_TEST_FULL_FILE_NAME)

# INFO: 
SELF_TEST_APPLICATIONS_FILE=		$(DIRS_BS_TEMP_DIR)/$(SELF_TEST_APPLICATIONS_FILE_NAME)
SELF_TEST_APPLICATIONS_DEEP_FILE=	$(DIRS_BS_TEMP_DIR)/$(SELF_TEST_APPLICATIONS_DEEP_FILE_NAME)
SELF_TEST_APPLICATIONS_FULL_FILE=	$(DIRS_BS_TEMP_DIR)/$(SELF_TEST_APPLICATIONS_FULL_FILE_NAME)

# INFO: 
SELF_TEST_MODULES_FILE=			$(DIRS_BS_TEMP_DIR)/$(SELF_TEST_MODULES_FILE_NAME)
SELF_TEST_MODULES_DEEP_FILE=		$(DIRS_BS_TEMP_DIR)/$(SELF_TEST_MODULES_DEEP_FILE_NAME)
SELF_TEST_MODULES_FULL_FILE=		$(DIRS_BS_TEMP_DIR)/$(SELF_TEST_MODULES_FULL_FILE_NAME)

# INFO: 
SELF_TEST_TOOLS_FILE=			$(DIRS_BS_TEMP_DIR)/$(SELF_TEST_TOOLS_FILE_NAME)
SELF_TEST_TOOLS_DEEP_FILE=		$(DIRS_BS_TEMP_DIR)/$(SELF_TEST_TOOLS_DEEP_FILE_NAME)
SELF_TEST_TOOLS_FULL_FILE=		$(DIRS_BS_TEMP_DIR)/$(SELF_TEST_TOOLS_FULL_FILE_NAME)

SELF_TEST_DEV_NULL_FILE=		/dev/null

$(SELF_TEST_FILE): \
		%: \
		$(SELF_TEST_APPLICATIONS_FILE)
	cp \
		$(SELF_TEST_DEV_NULL_FILE) \
		$*
	printf \
		$(SELF_TEST_RULE_FIRST_FORMATER) \
		'$$(CONFIG_SELF_TEST_RULE): \' \
		'$$(SELF_TEST_APPLICATIONS_RULE)' \
		>> \
		$*
	printf \
		$(SELF_TEST_RULE_SECOND_FORMATER) \
		'make \' \
		'$$(CONFIG_CLEAN_RULE)' \
		>> \
		$*

$(SELF_TEST_APPLICATIONS_FILE): \
		%: \
		$(SELF_TEST_MODULES_FILE)
	cp \
		$(SELF_TEST_DEV_NULL_FILE) \
		$*
	printf \
		$(SELF_TEST_BASE_FORMATER) \
		'$$(SELF_TEST_APPLICATIONS_RULE):' \
		>> \
		$*
	for \
		$(CONFIG_APPLICATION_PREFIX) \
		in \
		$(APPLICATIONS_PLATFORMS_LIST); \
		do \
			printf \
				$(SELF_TEST_LOOP_FIRST_FORMATER) \
				'\' \
				'$$(SELF_TEST_PREFIX)' \
				$$$(CONFIG_APPLICATION_PREFIX) \
				>> \
				$*; \
			printf \
				$(SELF_TEST_LOOP_SECOND_FORMATER) \
				'$$(SELF_TEST_PREFIX)' \
				$$$(CONFIG_APPLICATION_PREFIX) \
				'$$(SELF_TEST_PREFIX)_%:' \
				>> \
				$*; \
			printf \
				$(SELF_TEST_LOOP_THIRD_FORMATER) \
				'make \' \
				'$$(CONFIG_CLEAN_RULE)_$$*' \
				>> \
				$*; \
			printf \
				$(SELF_TEST_LOOP_THIRD_FORMATER) \
				'make \' \
				'$$*' \
				>> \
				$*; \
			printf \
				$(SELF_TEST_LOOP_LOG_FORMATER) \
				'echo \' \
				'$$* >> \' \
				'$$(SELF_TEST_PREFIX).$$(CONFIG_LOG_EXT)' \
				>> \
				$*; \
			printf \
				$(SELF_TEST_LOOP_LAST_FORMATER) \
				'$$(SELF_TEST_PREFIX)' \
				$$$(CONFIG_APPLICATION_PREFIX) \
				>> \
				$*; \
		done
	printf \
		$(SELF_TEST_EOF_APPLICATIONS_FORMATER) \
		'$$(SELF_TEST_MODULES_RULE)' \
		>> \
		$*

$(SELF_TEST_MODULES_FILE): \
		%: \
		$(SELF_TEST_TOOLS_FILE)
	cp \
		$(SELF_TEST_DEV_NULL_FILE) \
		$*
	printf \
		$(SELF_TEST_BASE_FORMATER) \
		'$$(SELF_TEST_MODULES_RULE):' \
		>> \
		$*
	for \
		$(CONFIG_MODULE_PREFIX) \
		in \
		$(MODULES_PLATFORMS_LIST); \
		do \
			printf \
				$(SELF_TEST_LOOP_FIRST_FORMATER) \
				'\' \
				'$$(SELF_TEST_PREFIX)' \
				$$$(CONFIG_MODULE_PREFIX) \
				>> \
				$*; \
			printf \
				$(SELF_TEST_LOOP_SECOND_FORMATER) \
				'$$(SELF_TEST_PREFIX)' \
				$$$(CONFIG_MODULE_PREFIX) \
				'$$(SELF_TEST_PREFIX)_%:' \
				>> \
				$*; \
			printf \
				$(SELF_TEST_LOOP_CONDITION_FORMATER) \
				'if [ -z "$$(shell grep $(SELF_TEST_GREP_FLAGS) $(SELF_TEST_GREP_MATCH_PATTERN) $(DEPENDENCIES_FILE) | tr -d \\\)" ]; then \' \
				'echo $$* never used >> \' \
				'$$(SELF_TEST_PREFIX).$$(CONFIG_LOG_EXT); \' \
				'fi' \
				>> \
				$*; \
			printf \
				$(SELF_TEST_LOOP_THIRD_FORMATER) \
				'make \' \
				'$$(CONFIG_CLEAN_RULE)_$$*' \
				>> \
				$*; \
			printf \
				$(SELF_TEST_LOOP_THIRD_FORMATER) \
				'make \' \
				'$$*' \
				>> \
				$*; \
			printf \
				$(SELF_TEST_LOOP_LOG_FORMATER) \
				'echo \' \
				'$$* >> \' \
				'$$(SELF_TEST_PREFIX).$$(CONFIG_LOG_EXT)' \
				>> \
				$*; \
			printf \
				$(SELF_TEST_LOOP_LAST_FORMATER) \
				'$$(SELF_TEST_PREFIX)' \
				$$$(CONFIG_MODULE_PREFIX) \
				>> \
				$*; \
		done
	printf \
		$(SELF_TEST_EOF_MODULES_FORMATER) \
		'$$(SELF_TEST_TOOLS_RULE)' \
		>> \
		$*

$(SELF_TEST_TOOLS_FILE): \
		%: | \
		$(DIRS_BS_TEMP_DIR)
	cp \
		$(SELF_TEST_DEV_NULL_FILE) \
		$*
	printf \
		$(SELF_TEST_BASE_FORMATER) \
		'$$(SELF_TEST_TOOLS_RULE):' \
		>> \
		$*
	for \
		$(CONFIG_TOOL_PREFIX) \
		in \
		$(TOOLS_PLATFORMS_LIST); \
		do \
			printf \
				$(SELF_TEST_LOOP_FIRST_FORMATER) \
				'\' \
				'$$(SELF_TEST_PREFIX)' \
				$$$(CONFIG_TOOL_PREFIX) \
				>> \
				$*; \
			printf \
				$(SELF_TEST_LOOP_SECOND_FORMATER) \
				'$$(SELF_TEST_PREFIX)' \
				$$$(CONFIG_TOOL_PREFIX) \
				'$$(SELF_TEST_PREFIX)_%:' \
				>> \
				$*; \
			printf \
				$(SELF_TEST_LOOP_CONDITION_FORMATER) \
				'if [ -z "$$(shell grep $(SELF_TEST_GREP_FLAGS) $(SELF_TEST_GREP_MATCH_PATTERN) $(DEPENDENCIES_FILE) | tr -d \\\)" ]; then \' \
				'echo $$* never used >> \' \
				'$$(SELF_TEST_PREFIX).$$(CONFIG_LOG_EXT); \' \
				'fi' \
				>> \
				$*; \
			printf \
				$(SELF_TEST_LOOP_THIRD_FORMATER) \
				'make \' \
				'$$(CONFIG_CLEAN_RULE)_$$*' \
				>> \
				$*; \
			printf \
				$(SELF_TEST_LOOP_THIRD_FORMATER) \
				'make \' \
				'$$*' \
				>> \
				$*; \
			printf \
				$(SELF_TEST_LOOP_LOG_FORMATER) \
				'echo \' \
				'$$* >> \' \
				'$$(SELF_TEST_PREFIX).$$(CONFIG_LOG_EXT)' \
				>> \
				$*; \
			printf \
				$(SELF_TEST_LOOP_LAST_FORMATER) \
				'$$(SELF_TEST_PREFIX)' \
				$$$(CONFIG_TOOL_PREFIX) \
				>> \
				$*; \
		done
	printf \
		$(SELF_TEST_RM_LOG_FORMATER) \
		'rm \' \
		'-f \' \
		'$$(SELF_TEST_PREFIX).$$(CONFIG_LOG_EXT)' \
		>> \
		$*
	printf \
		$(SELF_TEST_LOOP_THIRD_FORMATER) \
		'make \' \
		'$$(CONFIG_CLEAN_RULE)' \
		>> \
		$*
	echo \
		>> \
		$*

include $(SELF_TEST_FILE)
include $(SELF_TEST_APPLICATIONS_FILE)
include $(SELF_TEST_MODULES_FILE)
include $(SELF_TEST_TOOLS_FILE)

#$(SELF_TEST_DEEP_FILE): \
#		%: \
#		$(SELF_TEST_APPLICATIONS_DEEP_FILE)

#$(SELF_TEST_APPLICATIONS_DEEP_FILE): \
#		%: \
#		$(SELF_TEST_MODULES_DEEP_FILE)

#$(SELF_TEST_MODULES_DEEP_FILE): \
#		%: \
#		$(SELF_TEST_TOOLS_DEEP_FILE)

#$(SELF_TEST_TOOLS_DEEP_FILE): \
#		%: | \
#		$(DIRS_BS_TEMP_DIR)

#include $(SELF_TEST_DEEP_FILE)
#include $(SELF_TEST_APPLICATIONS_DEEP_FILE)
#include $(SELF_TEST_MODULES_DEEP_FILE)
#include $(SELF_TEST_TOOLS_DEEP_FILE)

#$(SELF_TEST_FULL_FILE): \
#		%: \
#		$(SELF_TEST_APPLICATIONS_FULL_FILE)

#$(SELF_TEST_APPLICATIONS_FULL_FILE): \
#		%: \
#		$(SELF_TEST_MODULES_FULL_FILE)

#$(SELF_TEST_MODULES_FULL_FILE): \
#		%: \
#		$(SELF_TEST_TOOLS_FULL_FILE)

#$(SELF_TEST_TOOLS_FULL_FILE): \
#		%: | \
#		$(DIRS_BS_TEMP_DIR)

#include $(SELF_TEST_FULL_FILE)
#include $(SELF_TEST_APPLICATIONS_FULL_FILE)
#include $(SELF_TEST_MODULES_FULL_FILE)
#include $(SELF_TEST_TOOLS_FULL_FILE)

endif

