ifndef MK_TEMPLATES_MK
MK_TEMPLATES_MK=			TRUE

INCLUDER_MODULES_LIST=			dirs \
					config \
					root
				
ifndef INCLUDER_PATH
$(error tool modbuild is not installed in your build system!)
else
include $(INCLUDER_PATH)
endif

TEMPLATE_DIR=				$(ROOT_DIR)/$(DIRS_TEMPLATES_DIR)

TEMPLATE_APPLICATION_FILE=		$(TEMPLATE_DIR)/$(CONFIG_DEFAULT_APPLICATION_BUILDSCRIPT_FILE_NAME)
TEMPLATE_MODULE_FILE=			$(TEMPLATE_DIR)/$(CONFIG_DEFAULT_MODULE_BUILDSCRIPT_FILE_NAME)
TEMPLATE_TOOL_FILE=			$(TEMPLATE_DIR)/$(CONFIG_DEFAULT_TOOL_BUILDSCRIPT_FILE_NAME)

endif

