ifndef MK_TRANSFER_MK
MK_TRANSFER_MK=				TRUE


INCLUDER_MODULES_LIST=			config \
					dirs

ifndef INCLUDER_PATH
$(error tool modbuild is not installed in your build system!)
else
include $(INCLUDER_PATH)
endif

TRANSFER_PREFIX=			transfer

TRANSFER_SRC_FILE_NAME=			$(TRANSFER_PREFIX)_$(DIRS_SOURCES_DIR).$(CONFIG_LIST_EXT)
TRANSFER_INCLUDE_FILE_NAME=		$(TRANSFER_PREFIX)_$(DIRS_INCLUDE_DIR).$(CONFIG_LIST_EXT)

TRANSFER_SRC_LIST_COMMAND=		cat \
						$(TRANSFER_SRC_FILE_NAME)

TRANSFER_INCLUDE_LIST_COMMAND=		cat \
						$(TRANSFER_INCLUDE_FILE_NAME)

TRANSFER_SRC_SED_PATTERN=		s/^$(DIRS_PULL_DIR)/$(DIRS_SOURCES_DIR)/

TRANSFER_INCLUDE_SED_PATTERN=		s/^$(DIRS_PULL_DIR)/$(DIRS_INCLUDE_DIR)/

TRANSFER_SRC_SED_COMMAND=		sed \
						$(TRANSFER_SRC_SED_PATTERN)

TRANSFER_INCLUDE_SED_COMMAND=		sed \
						$(TRANSFER_INCLUDE_SED_PATTERN)

endif
