ifndef MK_UNIT_TEST_SOURCES_MK
MK_UNIT_TEST_SOURCES_MK=		TRUE

INCLUDER_MODULES_LIST=			unit_test_sources/c

ifndef INCLUDER_PATH
$(error tool modbuild is not installed in your build system!)
else
include $(INCLUDER_PATH)
endif

UNIT_TEST_SOURCES_LIST=			$(UNIT_TEST_SOURCES_C_LIST)

UNIT_TEST_SOURCES_ENTRIES_LIST=		$(patsubst \
						$(DIRS_UNIT_TEST_SOURCES_DIR)/%_$(UNIT_TEST_SOURCES_C_EXT_SUFFIX), \
						%, \
						$(UNIT_TEST_SOURCES_LIST))

UNIT_TEST_SOURCES_TOOLS_DIR=		$(RELATIVE_ROOT_DIR)/$(DIRS_APPLICATIONS_DIR)
UNIT_TEST_SOURCES_INSTALL_DIR=		$(DIRS_INSTALL_DIR)/$(PLATFORM_HOST_ARCHITECTURE)

UNIT_TEST_SOURCES_TCUPPA_TOOL_NAME=	embunit_tcuppa
UNIT_TEST_SOURCES_BCUPPA_TOOL_NAME=	embunit_bcuppa

UNIT_TEST_SOURCES_TCUPPA_TOOL=		$(UNIT_TEST_SOURCES_INSTALL_DIR)/$(UNIT_TEST_SOURCES_TCUPPA_TOOL_NAME)_$(SIGNATURE_HOST_SUFFIX)
UNIT_TEST_SOURCES_BCUPPA_TOOL=		$(UNIT_TEST_SOURCES_INSTALL_DIR)/$(UNIT_TEST_SOURCES_BCUPPA_TOOL_NAME)_$(SIGNATURE_HOST_SUFFIX)

UNIT_TEST_SOURCES_TCUPPA_COMMAND=	$(UNIT_TEST_SOURCES_TOOLS_DIR)/$(UNIT_TEST_SOURCES_TCUPPA_TOOL_NAME)/$(UNIT_TEST_SOURCES_TCUPPA_TOOL)
UNIT_TEST_SOURCES_BCUPPA_COMMAND=	$(UNIT_TEST_SOURCES_TOOLS_DIR)/$(UNIT_TEST_SOURCES_BCUPPA_TOOL_NAME)/$(UNIT_TEST_SOURCES_BCUPPA_TOOL)

endif

