ifndef MK_REPO_INTERNAL_MK
MK_REPO_INTERNAL_MK=			TRUE

INCLUDER_MODULES_LIST=			config

ifndef INCLUDER_PATH
$(error tool modbuild is not installed in your build system!)
else
include $(INCLUDER_PATH)
endif

REPO_INTERNAL_REMOTE_NAME_DEFAULT=	origin
REPO_INTERNAL_REMOTE_NAME=		internal

REPO_INTERNAL_BRANCH_DEFAULT=		$(CONFIG_GITREPO_BRANCH_DEFAULT)

REPO_INTERNAL_GITREPO_EXISTENCE=	$(wildcard \
						$(CONFIG_PUSH_FILE_NAME))
ifneq ($(REPO_INTERNAL_GITREPO_EXISTENCE), )
REPO_INTERNAL_GITREPO_CONTENT_COMMAND=	cat \
						$(CONFIG_PUSH_FILE_NAME)

REPO_INTERNAL_GITREPO_CONTENT=		$(shell \
						$(REPO_INTERNAL_GITREPO_CONTENT_COMMAND))

REPO_INTERNAL_GITREPO_CONTENT_WORDS=	$(words \
						$(REPO_INTERNAL_GITREPO_CONTENT))

ifneq ($(REPO_INTERNAL_GITREPO_CONTENT_WORDS), 1)
ifneq ($(REPO_INTERNAL_GITREPO_CONTENT_WORDS), 2)
$(error $(CONFIG_PUSH_FILE_NAME) syntax mismatch)
else
REPO_INTERNAL_REPO_URL=			$(word \
						1, \
						$(REPO_INTERNAL_GITREPO_CONTENT))

REPO_INTERNAL_REPO_BRANCH=		$(word \
						2, \
						$(REPO_INTERNAL_GITREPO_CONTENT))
endif
else
REPO_INTERNAL_REPO_URL=			$(REPO_INTERNAL_GITREPO_CONTENT)
REPO_INTERNAL_REPO_BRANCH=		$(REPO_INTERNAL_BRANCH_DEFAULT)
endif
else
REPO_INTERNAL_REPO_URL=
REPO_INTERNAL_REPO_BRANCH=
endif

endif

